config/routes.rb
IndividualProjectAcnguye4::Application.routes.draw do
  resources :menus

  resources :tickets

  resources :ticket_infos

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :food_name, :price

   has_many :tickets
  has_many :ticket_infos, :through => :tickets
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :cooking, :food_name, :in_queue, :paid, :price, :quantity, :served, :subtotal, :tax, :total

  belongs_to :ticket_info
  belongs_to :menu

  before_save do
    total
  end
  def subtotal
    self.subtotal = self.price * self.quantity
  end

   def tax
     self.tax = self.subtotal * 0.0825
   end

  def total
    self.total = self.subtotal + self.tax
  end
end

app/models/ticket_info.rb
class TicketInfo < ActiveRecord::Base
  attr_accessible :cook, :guest_number, :table_number, :ticket_id, :waiter

  has_many :tickets
  has_many :menus, :through => :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ticket_infos_controller.rb
class TicketInfosController < ApplicationController
  # GET /ticket_infos
  # GET /ticket_infos.json
  def index
    @ticket_infos = TicketInfo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ticket_infos }
    end
  end

  # GET /ticket_infos/1
  # GET /ticket_infos/1.json
  def show
    @ticket_info = TicketInfo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket_info }
    end
  end

  # GET /ticket_infos/new
  # GET /ticket_infos/new.json
  def new
    @ticket_info = TicketInfo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket_info }
    end
  end

  # GET /ticket_infos/1/edit
  def edit
    @ticket_info = TicketInfo.find(params[:id])
  end

  # POST /ticket_infos
  # POST /ticket_infos.json
  def create
    @ticket_info = TicketInfo.new(params[:ticket_info])

    respond_to do |format|
      if @ticket_info.save
        format.html { redirect_to @ticket_info, notice: 'Ticket info was successfully created.' }
        format.json { render json: @ticket_info, status: :created, location: @ticket_info }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ticket_infos/1
  # PUT /ticket_infos/1.json
  def update
    @ticket_info = TicketInfo.find(params[:id])

    respond_to do |format|
      if @ticket_info.update_attributes(params[:ticket_info])
        format.html { redirect_to @ticket_info, notice: 'Ticket info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_infos/1
  # DELETE /ticket_infos/1.json
  def destroy
    @ticket_info = TicketInfo.find(params[:id])
    @ticket_info.destroy

    respond_to do |format|
      format.html { redirect_to ticket_infos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/ticket_infos_helper.rb
module TicketInfosHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividualProjectAcnguye4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_name %><br />
    <%= f.text_field :food_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Food name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.food_name %></td>
    <td><%= menu.price %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Food name:</b>
  <%= @menu.food_name %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/ticket_infos/_form.html.erb
<%= form_for(@ticket_info) do |f| %>
  <% if @ticket_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_info.errors.count, "error") %> prohibited this ticket_info from being saved:</h2>

      <ul>
      <% @ticket_info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :ticket_id %><br />
      <%= f.collection_select(:ticket_id,Ticket.all,:id,:id) %>
    </div>
  <div class="field">
    <%= f.label :table_number %><br />
    <%= f.number_field :table_number %>
  </div>
  <div class="field">
    <%= f.label :guest_number %><br />
    <%= f.number_field :guest_number %>
  </div>
  <div class="field">
    <%= f.label :waiter %><br />
    <%= f.text_field :waiter %>
  </div>
  <div class="field">
    <%= f.label :cook %><br />
    <%= f.text_field :cook %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_infos/edit.html.erb
<h1>Editing ticket_info</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_info %> |
<%= link_to 'Back', ticket_infos_path %>

app/views/ticket_infos/index.html.erb
<h1>Listing ticket_infos</h1>

<table>
  <tr>
    <th>Ticket</th>
    <th>Table number</th>
    <th>Guest number</th>
    <th>Waiter</th>
    <th>Cook</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ticket_infos.each do |ticket_info| %>
  <tr>
    <td><%= ticket_info.ticket_id %></td>
    <td><%= ticket_info.table_number %></td>
    <td><%= ticket_info.guest_number %></td>
    <td><%= ticket_info.waiter %></td>
    <td><%= ticket_info.cook %></td>
    <td><%= link_to 'Show', ticket_info %></td>
    <td><%= link_to 'Edit', edit_ticket_info_path(ticket_info) %></td>
    <td><%= link_to 'Destroy', ticket_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket info', new_ticket_info_path %>

app/views/ticket_infos/new.html.erb
<h1>New ticket_info</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_infos_path %>

app/views/ticket_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ticket:</b>
  <%= @ticket_info.ticket_id %>
</p>

<p>
  <b>Table number:</b>
  <%= @ticket_info.table_number %>
</p>

<p>
  <b>Guest number:</b>
  <%= @ticket_info.guest_number %>
</p>

<p>
  <b>Waiter:</b>
  <%= @ticket_info.waiter %>
</p>

<p>
  <b>Cook:</b>
  <%= @ticket_info.cook %>
</p>


<%= link_to 'Edit', edit_ticket_info_path(@ticket_info) %> |
<%= link_to 'Back', ticket_infos_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :food_name %><br />
      <%= f.collection_select(:food_name,Menu.all,:food_name,:food_name)  %>
    </div>
    <div class="field">
      <%= f.label :price %><br />
      <%= f.collection_select(:price,Menu.all,:price,:price)  %>
    </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :subtotal %><br />
    <%= f.text_field :subtotal %>
  </div>
  <div class="field">
    <%= f.label :tax %><br />
    <%= f.text_field :tax %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :in_queue %><br />
    <%= f.check_box :in_queue %>
  </div>
  <div class="field">
    <%= f.label :cooking %><br />
    <%= f.check_box :cooking %>
  </div>
  <div class="field">
    <%= f.label :served %><br />
    <%= f.check_box :served %>
  </div>
  <div class="field">
    <%= f.label :paid %><br />
    <%= f.check_box :paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Food name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Subtotal</th>
    <th>Tax</th>
    <th>Total</th>
    <th>In queue</th>
    <th>Cooking</th>
    <th>Served</th>
    <th>Paid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.food_name %></td>
    <td><%= ticket.price %></td>
    <td><%= ticket.quantity %></td>
    <td><%= ticket.subtotal %></td>
    <td><%= ticket.tax %></td>
    <td><%= ticket.total %></td>
    <td><%= ticket.in_queue %></td>
    <td><%= ticket.cooking %></td>
    <td><%= ticket.served %></td>
    <td><%= ticket.paid %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Food name:</b>
  <%= @ticket.food_name %>
</p>

<p>
  <b>Price:</b>
  <%= @ticket.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ticket.quantity %>
</p>

<p>
  <b>Subtotal:</b>
  <%= @ticket.subtotal %>
</p>

<p>
  <b>Tax:</b>
  <%= @ticket.tax %>
</p>

<p>
  <b>Total:</b>
  <%= @ticket.total %>
</p>

<p>
  <b>In queue:</b>
  <%= @ticket.in_queue %>
</p>

<p>
  <b>Cooking:</b>
  <%= @ticket.cooking %>
</p>

<p>
  <b>Served:</b>
  <%= @ticket.served %>
</p>

<p>
  <b>Paid:</b>
  <%= @ticket.paid %>
</p>


<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>